### ISSUE TITLE
Prüfen: customTexts im Booklet?????

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-ng#100]
customTexts sollte es eigenlich nur aus der app.config und aus dem login geben

**Comment by mechtelm** [comment]
Booklet-customTexts sind im FrontEnd abgeschafft (werden ignoriert)

**Comment by paflov** [comment]
dann werde ich ich sie auch backendseitig entfernen.

**Comment by paflov** [comment]
https://github.com/iqb-berlin/testcenter-iqb-php/issues/100

**Comment by mechtelm** [comment]
auch in der xsd umgesetzt
