### ISSUE TITLE
test-controller review: Eingabefeld für Name

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-ng#101]
Wenn (theoretisch und wahrscheinlich auch praktisch) review-modus mit einem direkten Link vorgenommen werden können und damit review-logins für einzelne Kolleginnen entfallen, sollte die Review-Box die Eingabe des Absendernamens erlauben (merken!).

**Comment by paflov** [comment]
Eigentlich ironisch, dass wir kurz vorher die Spalte `reviewer` auf der Datenbank entfernt hatten, weil sie nicht sinnvoll erschien... könnte man sonst auch wieder aufnehme..?
