### ISSUE TITLE
Vor/Zurück navigation im Anmeldeprozess funktioniert nicht

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-ng#109]
Ich logge mich ein, dann kommt die Code-Eingabe

* clickt man hier auf "zurück" passiert gar nichts

dann gebe ich den code ein

* clickt man hier auf zurück kommt  richtiger weise zur code Eingabe
 *clickt man hier noch mal auf zurück, landet man im Nirvana

**Comment by paflov** [comment]
Jetzt kann man auch nicht mehr zur Code-Eingabe zurück kehren. Ist das eine befriedigende Lösung?

**Comment by mechtelm** [comment]
Yo würde ich so sehen
