### ISSUE TITLE
Fehler auf der Konsole nach Neuladen ohne Anmeldung

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-ng#129]
Gibt man einen falschen Benutzernamen an, und läd dann mit neu (F5), landen seltsame Fehler auf der Konsole

```
ERROR TypeError: "authData.access is undefined"
    ngOnInit status-card.component.ts:26
    Angular 7
core.js:6185:19
ERROR TypeError: "can't convert undefined to object"
```

**Comment by mechtelm** [comment]
Konnte ich nicht nachvollziehen.

**Comment by paflov** [comment]
Hm OK, auch wenn es mir nicht sehr super erscheint, der Vollständigkeit halber eine Schritt für Schritt Rekonstruktion
* gehe auf https://ocba.iqb.hu-berlin.de
* lösche den localStorage um clean neu zustarten
* gebe xxx und xxx ein
* submit
-> man ist nicht angemeldet
* [F5] drücken
-> Konsole ist voller Fehler

**Comment by paflov** [comment]
![fehlerkonsole](https://user-images.githubusercontent.com/12844833/80574660-8d18c580-8a02-11ea-821b-8379c840d013.png)
