### ISSUE TITLE
Codeeingabe nach neu Anmeldung nicht möglich

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-ng#133]
* als Admin anmelden -> Workspace Übersicht erscheint
* auf zurück clicken
* mit (code benötigendem) login anmelden
* links steht "Sie sind mit Administrator-Funktionen angemeldet. Aktuell sind keine Studien für Sie freigegeben. ", es wird also das admin-modul geladen, rechts steht aber "Status: Angemeldet als "sample_group/test![anmeldungs-verwirrung.png](https://images.zenhubusercontent.com/5e723e7e176f1565210d36c8/faf59ac6-a353-4d73-b980-7097e74a813e)"

**Comment by mechtelm** [comment]
auf "zurück" klicken? das geht doch nicht

**Comment by paflov** [comment]
jetzt nicht mehr, hatte die letzte Änderung noch nicht. Aber man kann natürlich in der history zurück gehen...
