### ISSUE TITLE
Fehlermeldung, da log nach lock ausgeführt wird

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-ng#134]
# Fehlerbeschreibung
Bei Testabschluss wird log nach lock ausgeführt, was natürlich einen Fehler auslöst. 

# Getestet
**Server**: ocba, lokal
**Testdaten (player etc.)**: realworld-testdaten mit dan-player, sample-daten mit sample-player
**URL**: http://localhost:4200/#/r/test-starter
**Modus**: hot-run-restart
**Browser**: Firefox 68.7.0esr

![log-lock.png](https://images.zenhubusercontent.com/5e723e7e176f1565210d36c8/0542e5bc-51f3-468a-a2bb-b2363e9849ec)

**Comment by mechtelm** [comment]
Das war noch ein Unit-Log (try leave unit, kein Booklet log), ist gefixt.
