### ISSUE TITLE
[SysCheck] Anzeigen wie viele Runden noch folgen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-ng#30]
Teil 1 / 15 anzeigen
evtl. auch Fortschrittbalken

**Comment by schnitca** [comment]
kann Grafik vollständig ersetzen, falls wir/die EDV diese nicht für irgendwelche Zwecke brauchen

**Comment by mechtelm** [comment]
Fortschrittsanzeige: Ist umgesetzt.
Grafik bleibt.
