### ISSUE TITLE
[SysCheck] Toleranz für Speedtest wiederholungen vergrößern

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-ng#31]

**Comment by schnitca** [comment]
Die Grafik kann m.E. ausgeblendet werden. Gehe ich von mir aus, können Lehrkräfte damit nichts anfangen, es sei denn, sie beschäftigen sich damit. Dazu besteht aber in dem Systemcheck von Seiten der User*innen eigentlich kein Anlass.

**Comment by paflov** [comment]
Das bezieht sich darauf, dass Netze schnell als Instabil gewertet werden, weil einzelne Messungen als zu stark abweichend gewertet werden. Dort kann eine größere Toleranz angenommen werden.

**Comment by paflov** [comment]
done
