### ISSUE TITLE
Seltsame Fehlermeldung wenn man einen Personencode den es nicht gibt

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-ng#38]
Loggd man sich ein mit einem Testleiter, den es gibt, wählt dann aber einen nicht existierenden personencode, gibt es einen seltsamen Fehler. 
![image](https://user-images.githubusercontent.com/12844833/74255887-cf2f4680-4cf2-11ea-9852-a006f7c61b33.png)

**Comment by mechtelm** [comment]
Gefixt: Umstellung auf IqbComponents war nicht abgeschlossen.
