### ISSUE TITLE
Unit-Alias nicht konsequent verwendet

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-ng#51]
Bei getUnitData wird der Unit-Name verwendet, beim wegspeichern von RestorePoints etc. aber ggf. der alias. Folge: Beim Neuladen kommt kein RestorePoint, wenn ein Alias in der Booklet-Definition für diese Unit vergeben wurde.

Zu lösen ist es vermutlich so: [Hier](https://github.com/iqb-berlin/testcenter-iqb-ng/blob/98a41423464a74055b86734fa266635c14d2e402/src/app/test-controller/test-controller.component.ts#L308) muss der Unit-Name übergeben werden, nicht die Id.

**Comment by mechtelm** [comment]
Bei getUnitData MUSS die Unit-Id verwendet werden, da es sich ja hier nicht um die durchgeführte Unit handelt, sondern um die Unit-Definition. Nachfolgende Daten mit Bezug zur Unit müssen den Alias verwenden, da es sich dann um die durchgeführte/angewandte Unit handelt.
Habe den Alias-Kram durchgetestet, das ehemalige Problem mit einem falschen Log-Bezug hat sich durch die Umstellung des Routings gegeben.
