### ISSUE TITLE
Admin-UI weiß, ob im Workspace Testergebnisse und/oder SysCheck-Rückmeldungen vorliegen

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-ng#77]
Es ist verwirrend, dass die SysCheck-Definition mit den Testdefinitionen gemeinsam im Workspace liegen. Man könnte das als Konvention festlegen, dass also ein Workspace nur entweder oder genutzt werden sollte, man sollte das aber durch Konfiguration erzwingen.

**Comment by mechtelm** [comment]
Dementsprechend werden die Tabs eingeblendet.

**Comment by paflov** [comment]
rejected
