### ISSUE TITLE
[Admin-Results] CSV Spaltenköpfe Element-ID fehlen

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-ng#86]

**Comment by paflov** [comment]
Prüfen: Kann / Sollte das CSV nicht Backendseitig erzeugt werden werden wie bei Sys-Checks-Reports - wenn nichts dagegen spricht bitte Backend-Ticket anlegen.

https://github.com/iqb-berlin/testcenter-iqb-ng/blob/99c5972585d032b4f891a1f5ad8a5daf7c837ee7/src/app/workspace-admin/syscheck/syscheck.component.ts#L64

**Comment by paflov** [comment]
Wird sich erübrigen durch: https://github.com/iqb-berlin/testcenter-iqb-php/issues/112
