### ISSUE TITLE
PUT Test: Bookelt-ID prüfen?

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-ng#89]
Laden von Units schlägt fehl (OPTION ok, GET: 404; falscher Workspace 1 statt 17?

**Comment by mechtelm** [comment]
Läuft. Aber kann es sein, dass Du die ID bzw. den Namen des Booklet nicht überprüfst?

**Comment by paflov** [comment]
Stimmt. Man kann theoretisch nicht existierende Booklets starten. werden ich fixen.
